### PR TITLE
Project Templates

### PR DESCRIPTION
**Pull request by mpharrigan**
This is a serious wip, but it's solid work towards making msmbuilder actually usable.

The general idea is we will develop a set of short scripts that do common tasks, the user will run `msmb SetUpProject`, and it'll dump a variety of scripts that will serve as a good starting point.

This PR also includes a new dataset idiom including a persistent pandas dataframe that keeps a mapping from a consistent set of keys (the dataframe index) to trajectory filenames and other metadata (topology filename, number of frames, whatever you want ... the user is encouraged to modify the "generate-metadata" script)

Data is still saved as a bunch of numpy files in a directory, but now instead of trying to walk the filesystem to find files, we use the dataframe to find everything we're looking for.

My grand plan is to get these scripts pretty solid for a "generic" project where trajectories are keyed on integers, and then start including fah-specific scripts [primarily modifying the metadata part] that set up a multi-indexed dataframe (proj,run,clone) and saves trajectory files in a proj/run/clone.npy hierarchy on the filesystem.

This PR ropes in #747 with modifications.

I think the existing dataset infrastructure is overkill in terms of lazy-loading. The amount of GB of data is low for everything besides featurization, so we can shove our whole dataset into memory.

For example, 1 millisecond of data saved every 1 ns with 1000 features as 32-bit floats is only 4GB. That being said, we'll still have to do the initial featurization in a memory-efficient manner

One of my grander plans is to change from treating "lists of timeseries-arrays" as the thing that flows through our estimators to "dictionaries of timeseries-arrays". I imagine modifying our `transform` wrapper to return a list if a list is given and a dictionary if a dictionary is given, for backwards compatibility.

1. the trajectories are inherently not in any order, as implied by a list
2. meaningful keys are often non-sequential. This puts undue burden on the user to keep track of a mapping from "real keys" to list indices
3. people want non-integer keys. For FAH-style projects, keying by (proj,run,clone) would be nice. Strings could be used to label trajectories "apo" or "bound".

For now, the scripts will include
```python
out = {}
for k, traj in trajs:
  out[k] = estimator.partial_transform(traj)
```

But it would be nice to just do
```python
out = estimator.transform(trajs)
```

### CODE REVIEW

**Comment by msultan** [comment]
wow that is an impressive amount of work @mpharrigan . +1000 on switching over to using dictionaries instead of the list of lists.

**Comment by msultan** [comment]
this is freakin awesome.

**Comment by mpharrigan** [comment]
I worked on the new `dataset2` (final name tbd) module some more. Check out the scripts to see if you like the general idea. The major change is that it keeps a little dataframe around whenever it does saving and loading. I gave everything defaults where it expects to find this at `meta.pandas.pickl`, so you don't have to type it everywhere if you just use that filename. The general flow is

```python
meta, trajs = load_trajs('whatever-the-directory-is-named/')
print(meta['step_ps'].sum() / 1000, 'ns') # you can use meta data
new_trajs = {}
for k, v in trajs.items():
  new_trajs[k] = estimator.partial_transform(v)
save_trajs(new_trajs, 'new-directory-name', meta)
```

There are also `save_meta`, `save_generic` and their loaders which are convenience functions for persisting the meta dataframe and estimators/anything-picklable resp.

All the save functions will make a backup of the destination file (if it already exists) before writing

**Comment by mpharrigan** [comment]
And if we change the behavior of transform to return dictionaries when given dictionaries,

```python
meta, trajs = load_trajs('whatever-the-directory-is-named/')
new_trajs = estimator.transform(trajs)
save_trajs(new_trajs, 'new-directory-name', meta)
save_generic(estimator, 'estimator.pickl')
```

**Comment by mpharrigan** [comment]
I added an option to generate ipython notebooks instead of scripts. In the template scripts, start a line with double hashtag comment to split cells

**Comment by mpharrigan** [comment]
I added a "flavor" flag that let's you add different templates. For example, I added some fah-specific code (that sets up a proj,run,clone,gen index for your dataframe) that you'll only get if you use `msmb SetUpProject --flavor fah`

I added a `--steps` flag, so you can request only some of the templates

I renamed `dataset2` to `msmbuilder.io`, so it can peacefully coexist with `msmbuilder.dataset`

**Comment by mpharrigan** [comment]
These templates will all be under the MIT license, which is more permissive than msmbuilder itself

**Comment by msultan** [comment]
i keep getting errors when i try to run this. I think i might be missing something. 

``` bash
msmb ProjectTemplate --flavor generic
An unexpected error has occurred with MSMBuilder (version 3.5.0.dev0.dev-58a13dc), please
consider sending the following traceback to MSMBuilder GitHub issue tracker at:
            https://github.com/msmbuilder/msmbuilder/issues

Traceback (most recent call last):
  File "/Users/muneeb/anaconda/bin/msmb", line 9, in <module>
    load_entry_point('msmbuilder==3.5.0.dev0', 'console_scripts', 'msmb')()
  File "/Users/muneeb/anaconda/lib/python3.5/site-packages/msmbuilder-3.5.0.dev0-py3.5-macosx-10.5-x86_64.egg/msmbuilder/scripts/msmb.py", line 28, in main
    app.start()
  File "/Users/muneeb/anaconda/lib/python3.5/site-packages/msmbuilder-3.5.0.dev0-py3.5-macosx-10.5-x86_64.egg/msmbuilder/cmdline.py", line 464, in start
    instance.start()
  File "/Users/muneeb/anaconda/lib/python3.5/site-packages/msmbuilder-3.5.0.dev0-py3.5-macosx-10.5-x86_64.egg/msmbuilder/commands/project.py", line 31, in start
    self.instance.write_all()
  File "/Users/muneeb/anaconda/lib/python3.5/site-packages/msmbuilder-3.5.0.dev0-py3.5-macosx-10.5-x86_64.egg/msmbuilder/io.py", line 392, in write_all
    for k, ext, rendered in self.render_iter():
  File "/Users/muneeb/anaconda/lib/python3.5/site-packages/msmbuilder-3.5.0.dev0-py3.5-macosx-10.5-x86_64.egg/msmbuilder/io.py", line 376, in render_iter
    templ_dict = self.get_templates(env.list_templates())
  File "/Users/muneeb/anaconda/lib/python3.5/site-packages/jinja2/environment.py", line 723, in list_templates
    x = self.loader.list_templates()
  File "/Users/muneeb/anaconda/lib/python3.5/site-packages/jinja2/loaders.py", line 265, in list_templates
    _walk(path)
  File "/Users/muneeb/anaconda/lib/python3.5/site-packages/jinja2/loaders.py", line 259, in _walk
    for filename in self.provider.resource_listdir(path):
  File "/Users/muneeb/anaconda/lib/python3.5/site-packages/setuptools-20.3-py3.5.egg/pkg_resources/__init__.py", line 1466, in resource_listdir
  File "/Users/muneeb/anaconda/lib/python3.5/site-packages/setuptools-20.3-py3.5.egg/pkg_resources/__init__.py", line 1554, in _listdir
FileNotFoundError: [Errno 2] No such file or directory: '/Users/muneeb/anaconda/lib/python3.5/site-packages/msmbuilder-3.5.0.dev0-py3.5-macosx-10.5-x86_64.egg/msmbuilder/project_templates'

```

**Comment by mpharrigan** [comment]
Oh. good point. I've only been testing it with `python setup.py develop`, so the new files aren't getting installed (but it happens to work with develop because they don't *need* to be installed). I'll fix

**Comment by msultan** [comment]
few notes: 
- I would recommend some kind of folder system since even for a small dataset this is creating  a lot of files. Something like data folder, scripts folder, model folder. within the model folder we can have mdl_visualization folder etc. What I have currently 
```
Base dir
yaml_file describing project 
|-->data_dir
    |-->trajectories 
    |-->features_for_mdl1
    |-->features_for_mdl2
|-->mdl1
   |-->yaml_file describing model 1
   |-->model output files
|-->mdl2
   |-->yaml_file describing model 2
   |-->model output files
|-->mdl3
   |-->yaml_file describing model 3
   |-->model output files
|-->scripts
|-->ipython notebook which can load any of the mdl directories for visualization 
```

- within the model folder it would be nice to have a yaml/json file with model parameters dumped in as strings. 
- Ability to load the yaml file to fit a new variant to the model have the results dumped into the same/new mdl directory. 
- +1 on the dataframe. I can imagine that being very useful for sticking in other metadata like important residues or atom indices etc instead of having to regenerate them every time. 

I am still playing around with this but once i think of other things, i will add them here.

**Comment by mpharrigan** [comment]
Changed this to produce a hierarchical layout.

These are the files after running all the scripts (up to tica stage)
```
.
├── 0-test-install.py
├── 0-test-install.py.bak.1
├── 1-get-example-data.py
├── 1-get-example-data.py.bak.1
├── analysis
│   ├── dihedrals
│   │   ├── featurize-plot.py
│   │   ├── featurize.py
│   │   ├── featurizer.pickl
│   │   ├── ftrajs
│   │   │   ├── 10.npy
│   │   │   └── 9.npy
│   │   ├── meta.pandas.pickl -> ../meta.pandas.pickl
│   │   ├── tica
│   │   │   ├── ftrajs -> ../ftrajs
│   │   │   ├── meta.pandas.pickl -> ../meta.pandas.pickl
│   │   │   ├── msm
│   │   │   │   ├── cluster-plot.py
│   │   │   │   └── cluster.py
│   │   │   ├── tica-dimension-0-heatmap.pdf
│   │   │   ├── tica-dimension-0-inds.pickl
│   │   │   ├── tica-dimension-0.xtc
│   │   │   ├── tica-heatmap.pdf
│   │   │   ├── tica.pickl
│   │   │   ├── tica-plot.py
│   │   │   ├── tica.py
│   │   │   ├── tica-sample-coordinate-plot.py
│   │   │   ├── tica-sample-coordinate.py
│   │   │   ├── tica-timescales.pdf
│   │   │   ├── top.pdb -> ../../top.pdb
│   │   │   ├── trajs -> ../../trajs
│   │   │   └── ttrajs
│   │   │       ├── 10.npy
│   │   │       ├── 11.npy
│   │   │       └── 9.npy
│   │   ├── top.pdb -> ../top.pdb
│   │   └── trajs -> ../trajs
│   ├── gather-metadata-plot.py
│   ├── gather-metadata.py
│   ├── landmarks
│   │   ├── centroids.xtc
│   │   ├── clusterer.pickl
│   │   ├── featurize-plot.py
│   │   ├── featurize.py
│   │   ├── ftrajs
│   │   │   ├── 10.npy
│   │   │   ├── 8.npy
│   │   │   └── 9.npy
│   │   ├── ktrajs
│   │   │   ├── 10.npy
│   │   │   └── 9.npy
│   │   ├── meta.pandas.pickl -> ../meta.pandas.pickl
│   │   ├── rmsd-ktrajs-statecount.pdf
│   │   ├── rmsd-ktrajs-statehist.pdf
│   │   ├── tica
│   │   │   ├── ftrajs -> ../ftrajs
│   │   │   ├── meta.pandas.pickl -> ../meta.pandas.pickl
│   │   │   ├── msm
│   │   │   │   ├── cluster-plot.py
│   │   │   │   └── cluster.py
│   │   │   ├── tica-dimension-0-heatmap.pdf
│   │   │   ├── tica-dimension-0-inds.pickl
│   │   │   ├── tica-dimension-0.xtc
│   │   │   ├── tica-heatmap.pdf
│   │   │   ├── tica.pickl
│   │   │   ├── tica-plot.py
│   │   │   ├── tica.py
│   │   │   ├── tica-sample-coordinate-plot.py
│   │   │   ├── tica-sample-coordinate.py
│   │   │   ├── tica-timescales.pdf
│   │   │   ├── top.pdb -> ../../top.pdb
│   │   │   ├── trajs -> ../../trajs
│   │   │   └── ttrajs
│   │   │       ├── 10.npy
│   │   │       ├── 8.npy
│   │   │       └── 9.npy
│   │   ├── top.pdb -> ../top.pdb
│   │   └── trajs -> ../trajs
│   ├── meta.pandas.pickl
│   ├── top.pdb -> ../top.pdb
│   └── trajs -> ../trajs
├── analysis.bak.1
│   ├── dihedrals
│   │   ├── diheds
│   │   │   ├── 10.npy
│   │   │   └── 9.npy
│   │   ├── diheds.pickl
│   │   ├── featurize-plot.py
│   │   ├── featurize.py
│   │   ├── ftrajs-box.pdf
│   │   ├── meta.pandas.pickl -> ../meta.pandas.pickl
│   │   ├── tica
│   │   │   ├── msm
│   │   │   │   ├── cluster-plot.py
│   │   │   │   └── cluster.py
│   │   │   ├── tica-plot.py
│   │   │   ├── tica.py
│   │   │   ├── tica-sample-coordinate-plot.py
│   │   │   └── tica-sample-coordinate.py
│   │   ├── top.pdb -> ../top.pdb
│   │   └── trajs -> ../trajs
│   ├── gather-metadata-plot.py
│   ├── gather-metadata.py
│   ├── landmarks
│   │   ├── featurize-plot.py
│   │   ├── featurize.py
│   │   ├── meta.pandas.pickl -> ../meta.pandas.pickl
│   │   ├── tica
│   │   │   ├── msm
│   │   │   │   ├── cluster-plot.py
│   │   │   │   └── cluster.py
│   │   │   ├── tica-plot.py
│   │   │   ├── tica.py
│   │   │   ├── tica-sample-coordinate-plot.py
│   │   │   └── tica-sample-coordinate.py
│   │   ├── top.pdb -> ../top.pdb
│   │   └── trajs -> ../trajs
│   ├── lengths.pdf
│   ├── meta.pandas.html
│   ├── meta.pandas.pickl
│   ├── top.pdb -> ../top.pdb
│   └── trajs -> ../trajs
├── fs_peptide
│   ├── 100-fs-peptide-400K.pdb
│   ├── fs-peptide.pdb
│   ├── post-process.py
│   ├── simulate_fs.py
│   ├── trajectory-10.xtc
│   ├── trajectory-8.xtc
│   └── trajectory-9.xtc
├── README.md
├── README.md.bak.1
├── top.pdb -> fs_peptide/fs-peptide.pdb
└── trajs -> fs_peptide/
```

**Comment by mpharrigan** [comment]
Today's commits beefs up the power of the templating system. I've refactored the code for setting up plotting to a template file that gets `include`d. To show how this is valuable, there are new template rendering arguments `use_agg`, `use_xdgopen`, and `ipynb`

`ipynb` will render as ipython notebooks and use `%matplotlib inline`. Use the `--ipynb` command line flag.

`use_agg` and `use_xdgopen` are controlled by the `--display` command line flag. If you're working interactively, pass this flag and matplotlib will use its default rendered (which requires a screen) and `xdg-open` will be used to launch a pdf view of your plots as they're generated. Omit this flag if you're working on a server without X11 or xdg-open, and matplotlib will use the `Agg` backend and save pdf plots

**Comment by mpharrigan** [comment]
Today's updates

 - include a script for loading things into vmd (we should have this whereever relevant, so more tcl on the way)
 - rename some stuff
 - add options `--root` and `--step` to only render certain templates / parts of the complete workflow
 - general tidying and docs

In the near-term, I'm going to finish updating docs, finish randomly renaming files and function names and merge this. It will still be incomplete, but I want it in master so others start toying around with it. It will also come with a loose commitment that I'll stop with the major refactors and just *add* functionality. I'm not promising complete api stability until the release of 3.6.

**Comment by mpharrigan** [comment]
latest commit expands tutorial

**Comment by mpharrigan** [comment]
Going to make sure the tests pass and merge this soon. Going to need people to test it before we release 3.6 cc gh-836

**Pull request merged**
