### PR TITLE
Fix Conda Build errors

### PR DESCRIPTION
**Pull request by cxhernandez**
This fixed things locally for me. Hopefully, this isn't compromising the build workflow in any way.

### CODE REVIEW

**Comment by cxhernandez** [comment]
yayy they finally run!

**Comment by cxhernandez** [comment]
There's a lot of errors from the GHMM code. Was this part of the code changed recently?

**Comment by mpharrigan** [comment]
why did you remove numpy x.x ? that's there for a reason

**Comment by cxhernandez** [comment]
Locally, that was giving me a deprecation warning with the latest version of conda-build.

**Comment by mpharrigan** [comment]
Do you want to investigate what the preferred solution is to depend on a specific numpy ABI if not `numpy x.x`?

**Comment by cxhernandez** [comment]
https://conda.io/docs/building/variants.html#customizing-compatibility

**Comment by cxhernandez** [comment]
https://conda.io/docs/user-guide/tasks/build-packages/variants.html#conda-variables-and-command-line-arguments-to-conda-build

>To ensure consistency with existing users of conda-build, environment variables such as CONDA_PY behave as they always have, and they overwrite all variants set in files or passed to the API.

Does this mean we might not need this if those variables are set?

**Comment by cxhernandez** [comment]
Yeah, just checked locally. This seems to work.

**Comment by cxhernandez** [comment]
UPDATE: I don't care enough to understand the new system. I'm pinning to conda-build v2 (which conda-forge uses) and hoping for the best.

**Comment by cxhernandez** [comment]
Okay seems like there's some issues with HMMLearn. `model.sample(N)` results in an array of `None` objects.

**Comment by cxhernandez** [comment]
The only reason `hmmlearn` v0.1.1 was building on omnia was because it didn't have any unit tests.... the latest version fails for 4 and throws errors in 39 using `numpy` 1.12. I vote we get rid of this as a test dependency, if possible.

**Comment by msultan** [comment]
Can we block the ghmm test for the time being and merge this? There are several PRs that are being blocked by this.

**Comment by mpharrigan** [comment]
also I realized we don't need `numpy x.x` to run the tests because it will automatically test against the same numpy version that was used to build (if you keep the environment variable)

AND conda-forge has a new cockamamy scheme that doesn't pin to numpy and use `x.x`

**Comment by brookehus** [comment]
+1 to @msultan's comment

**Comment by brookehus** [comment]
@msmbuilder/developers, when @cxhernandez gets back let's prioritize getting this fixed

**Comment by cxhernandez** [comment]
Now there are issues with MDTraj testing data having been removed. Working on this now...

**Comment by cxhernandez** [comment]
Looks like someone broke RMSD in mdtraj v1.9. When I pin to 1.8.0, the tests work.

**Comment by cxhernandez** [comment]
yay!

**Comment by cxhernandez** [comment]
It seems that `Win` doesn't have the latest version of `statsmodels` yet (re: https://github.com/statsmodels/statsmodels/issues/3752).

**Comment by msultan** [comment]
Thank you @cxhernandez !

**Comment by cxhernandez** [comment]
So the GHMM tests just required `startprob_` to be initialized. Apparently between versions, this became necessary for sampling from the GHMM class -__-

**Pull request merged**
