### PR TITLE
SparseTICA improvements

### PR DESCRIPTION
**Pull request by mpharrigan**
- [x] Implement feature / fix bug
 - [ ] Add tests
 - [ ] Update changelog

I'm trying to just do sparse tica on the vonmises features for the example fs peptide data. I came across these bugs, but even with these fixes the heatmap looks positively whacky, so I suspect there's something else going on as well

### CODE REVIEW

**Comment by mpharrigan** [comment]
The lack of sorting is a pretty big deal, I think. So anyone who used this in production should probably review their work

**Comment by mpharrigan** [comment]
Or is `speigh` supposed to sort automatically? In practice this doesn't seem to be happening

**Comment by mpharrigan** [comment]
screenshot from 2016-03-19 16 46 05

 1. download fs peptide
 2. use von mises featurizer with default arguments
 3. transform with sparse tica

**Comment by mpharrigan** [comment]
```
In [14]: t.eigenvalues_
Out[14]: array([ 0.99025034,  0.98690298,  0.98711887,  0.99172246,  0.98582245])
```

**Comment by rmcgibbo** [comment]
Speigh is only a local optimizer that finds a single pseudo eigenvector starting from some initial guess, so you really can't be completely sure that you get them in sorted order.

**Comment by cxhernandez** [comment]
good catch @mpharrigan!

**Comment by mpharrigan** [comment]
@rmcgibbo, should we sort them after? should we set the number of components higher than what the user requests, sort, and then truncate?

**Comment by rmcgibbo** [comment]
Sorting after is fine. I don't think you should set the number of
components higher than the user requests though. That's not guaranteed to
find the global max either. Better to just inform users that this is how it
works, and they can set the number of components themselves.

On Mon, Mar 21, 2016 at 2:31 AM, Matthew Harrigan <notifications@github.com>
wrote:

> @rmcgibbo <https://github.com/rmcgibbo>, should we sort them after?
> should we set the number of components higher than what the user requests,
> sort, and then truncate?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/msmbuilder/msmbuilder/pull/767#issuecomment-199145517>
>



-- 
-Robert

**Comment by mpharrigan** [comment]
Ok, I added a note and we'll keep the sorting code (and addition of kinetic_map)

**Comment by mpharrigan** [comment]
Still wondering why my fs-peptide heatmap is so wonky

**Comment by mpharrigan** [comment]
Also removed the mention of cvxpy, which is no longer required

**Pull request merged**
