### PR TITLE
MAINT: Win-64 long/intp

### PR DESCRIPTION
**Pull request by rmcgibbo**

### CODE REVIEW

**Comment by mpharrigan** [comment]
looks like you missed a couple?

**Comment by rmcgibbo** [comment]
@mpharrigan, right now both you and I have appveyor set up to build the same repo

- https://ci.appveyor.com/project/rmcgibbo/msmbuilder/build/1.0.389
- https://ci.appveyor.com/project/MatthewHarrigan/msmbuilder/build/1.0.118

**Comment by mpharrigan** [comment]
ok i deleted it

**Comment by rmcgibbo** [comment]
got a pass on py27-x64.

**Comment by rmcgibbo** [comment]
Still one issue on py34-x64. Not sure, but merging anyways.

**Pull request merged**
