### PR TITLE
Re-do runtests.py

### PR DESCRIPTION
**Pull request by mpharrigan**
addresses #706

### CODE REVIEW

**Comment by mpharrigan** [comment]
This simplifies test discovery/running by just using `subprocess` with a modified `PYTHONPATH`

**Comment by rmcgibbo** [comment]
why not just add an `msmbuilder.test()` function like mdtraj?

**Comment by mpharrigan** [comment]
I couldn't get that to work (tried it). 

I suspect the fact that `import msmbuilder` doesn't import everything makes the test discovery not work

**Comment by rmcgibbo** [comment]
> I suspect the fact that import msmbuilder doesn't import everything makes the test discovery not work
 Hide all checks

I doubt that, based on the existence of `scipy.test()`. But it's not important.

**Comment by mpharrigan** [comment]
Ok, I was probably doing something wrong, but I couldn't get programmatic test discovery to work :)

This does work though!

**Pull request merged**
