### PR TITLE
Documentation updates 2

### PR DESCRIPTION
**Pull request by mpharrigan**
Finalize deployment.

### CODE REVIEW

**Comment by mpharrigan** [comment]
Note that the docs from #614 can be seen here http://msmbuilder.org/test-deploy/development/html/index.html

**Comment by rmcgibbo** [comment]
looks good.

**Comment by rmcgibbo** [comment]
what would be really sick is if we could connect the head maps with the mdtraj webgl protein visualizer in the tutorial.

**Comment by mpharrigan** [comment]
Now here: http://msmbuilder.org/development/

**Pull request merged**
