### PR TITLE
PR for describe_features method

### PR DESCRIPTION
**Pull request by msultan**
This PR implements the describe_features method for 3 of the most commonly used featurziers ```ContactFeaturizer, DihedralFeaturizer, & KappaAngleFeaturizer```. Most, if not all, of the code was inspired by Kyle's previous attempt to get this going. 

For the ```DihedralFeaturizer``` 
```python

In [13]: f=DihedralFeaturizer()

In [14]: df = pd.DataFrame(f.describe_features(t))

In [15]: df[:1]
Out[15]: 
            atomind  bigclass otherInfo  resSeq   resid     resname smallclass
0  [22, 24, 26, 34]  dihedral       sin  [1, 2]  [0, 1]  [LYS, ASP]        phi
```

For the ```ContactFeaturizer``` 
```python
In [16]: f = ContactFeaturizer()

In [17]: df = pd.DataFrame(f.describe_features(t))
 
In [18]: df[:1]
Out[18]: 
  atomind bigclass otherInfo  resSeq   resid     resname     smallclass
0     N/A      all      True  [1, 4]  [0, 3]  [LYS, TRP]  closest-heavy
```

For the ```KappaAngleFeaturizer```
```python
In [26]: f = KappaAngleFeaturizer()

In [27]: df = pd.DataFrame(f.describe_features(t))

In [28]: df[:1]
Out[28]: 
       atomind bigclass otherInfo     resSeq      resid          resname  \
0  [4, 38, 78]    angle       cos  [1, 3, 5]  [0, 2, 4]  [LYS, VAL, GLU]   

  smallclass  
0      kappa 
 ```

### CODE REVIEW

**Comment by msultan** [comment]
wait a minute. let me upload the latest version.

**Comment by rmcgibbo** [comment]
Does it need to return a pandas df, or can it just be a list of the feature names?

**Comment by msultan** [comment]
It returns a list of dictionaries that individually describe the features. We dont really need pandas. Thats just to collect everything in the end.  

```python
In [12]: type(f.describe_features(t))
Out[12]: list

In [13]: f.describe_features(t)[0]
Out[13]: 
{'atomind': array([ 4, 38, 78]),
 'bigclass': 'angle',
 'otherInfo': 'cos',
 'resSeq': array([1, 3, 5]),
 'resid': array([0, 2, 4]),
 'resname': ['LYS', 'VAL', 'GLU'],
 'smallclass': 'kappa'}

```

**Comment by rmcgibbo** [comment]
The docstrings say pandas.

**Comment by msultan** [comment]
Woops, should be okay now.

**Pull request merged**
