### PR TITLE
Release 3.8.0

### PR DESCRIPTION
**Pull request by brookehus**

### CODE REVIEW

**Comment by msultan** [comment]
wohooo, we are at #1000 PRs! Congrats @brookehus !

**Comment by brookehus** [comment]
ice cream party?

**Comment by cxhernandez** [comment]
No, that's only for serious occasions.

**Comment by msultan** [comment]
yea like 90 days without stats issues on Folding@home. A feat that was accomplished by yours truly and @cxhernandez back in 2014.

**Comment by cxhernandez** [comment]
Speaking of, [we're about to celebrate 1000 days soon](https://www.google.com/search?q=days+since+septermber+24th+2014) 😄

**Pull request merged**
