### PR TITLE
Automatic State Partitioning for Multibody Systems (APM)

### PR DESCRIPTION
**Pull request by stephenliu1989**
# Automatic State Partitioning for Multibody Systems (APM)
### 1. Introduction
This Program is a python package which implements Automatic State Partitioning for Multibody Systems (APM) algorithm to cluster trajectories and model the transitions based on a Markov state models (MSMs). The conformational dynamics of multibody systems plays crucial roles in many important problems. MSMs are powerful kinetic network models that can predict long-time-scale dynamics using many short molecular dynamics simulations. Although MSMs have been successfully applied to conformational changes of individual proteins, the analysis of multibody systems is still a challenge because of the complexity of the dynamics that occur on a mixture of drastically different time scales. APM is designed for constructing MSMs to elucidate the conformational dynamics of multibody systems. The APM algorithm effectively addresses different time scales in the multibody systems by directly incorporating dynamics into geometric clustering when identifying the metastable conformational states. We have applied the APM algorithm to a 2D potential that can mimic a protein−ligand binding system and the aggregation of two hydrophobic particles in water and have shown that it can yield tremendous enhancements in the computational efficiency of MSM construction and the accuracy of the models.

### 2. System Requirement
- Python 2.7.10
- Numpy 1.9.2
- Scipy 0.15.1
- Scikit-learn 0.16.1
- Matplotlib 1.4.3
- MDTraj 1.3.0
- MSMBuilder 3.2.0

### 3. Documentation
The Doxygen documentation for this code can be found at [doc](http://chz382.ust.hk/doc/stephen/MSMB_APM/).

### 4. Install Python and Python Packages
We highly recommend that you download the Python 2.7 version of Anaconda, which is a completely free enterprise-ready Python distribution for large-scale data processing, predictive analytics, and scientific computing.

#### - 2D Potential
		cd test_2D_potential/
		python test_apm_2d.py 
	
***optional arguments:***
   	 	-h, --help            show this help message and exit
    	-t TRAJLISTFNS, --trajListFns TRAJLISTFNS
                          List of trajectory files to read in, separated by
                          spaces.
    	-a ATOMLISTFNS, --atomListFns ATOMLISTFNS
                          List of atom index files to read in, separated by
                          spaces.
    	-g TOPOLOGY, --topology TOPOLOGY
                          topology file.
    	-e IEXT, --iext IEXT  The file extension of input trajectory files. Must be
                          a filetype that mdtraj.load() can recognize.
    	-s STRIDE, --stride STRIDE
                          stride.
    	-m N_MACROSTATES, --n_macrostates N_MACROSTATES
                          n_macrostates.
    	-l LAG_TIME, --lag_time LAG_TIME
                          lag_time.
    	-i MAX_ITER, --max_iter MAX_ITER
                          max_iter.
    	-c SUB_CLUSTER, --sub_cluster SUB_CLUSTER
                          sub_cluster.  

#### References
**Fu Kit SHEONG, …, Xuhui HUANG**, [“Automatic State Partitioning for Multibody Systems (APM): An Efficient Algorithm for Constructing Markov State Models To Elucidate Conformational Dynamics of Multibody Systems”](http://pubs.acs.org/doi/abs/10.1021/ct5007168), **J. Chem. Theory Comput., 2015, 11 (1), pp 17–27**

#### Credits:
**Code Author:** [LIU Song](http://chz382.ust.hk/u/stephen): *stephenliu1989@gmail.com*
**Contributors:** Fukit SHEONG, Xuhui HUANG
Copyright (c) 2015, Hong Kong University of Science and Technology (HKUST)

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Hi @stephenliu1989.

Thanks for contributing this!

Part of our process is code review, where before merging code into the master branch we try to get it in tip-top shape. In our experience, some of the things which "make sense" for writing scripts and debugging your own personal code sometimes need to be adapted for code that is indented to be distributed as part of a software library, and we want to make sure MSMBuilder has as high standards of software engineering as possible.

So I'm going to make some comments, both below and directly in the code, and recommend some changes to make. Please don't take them negatively or in the wrong way -- it's all about working together to build the best releases possible.

**Comment by rmcgibbo** [comment]
1. You'll need to add some tests. See examples in https://github.com/msmbuilder/msmbuilder/tree/master/msmbuilder/tests. At minimum, the tests need to just run the code, and verify that when given the appropriate types of inputs it runs correctly and doesn't crash.
2. The code needs to run on multiple versions of Python. MSMBuilder supports Python 2.7, 3.3, 3.4, and 3.5. It looks like the, in it's current state, this code doesn't support Python 3 because of the use of the legacy print statement.
3. It's not appropriate for the library to write out files to disk, as is done on lines 139-140.

In order to fix the code for python 3, I would recommend running `pip install future yapf; futurize -1 msmbuilder/apm/apm_.py; yapf -i msmbuilder/apm/apm_.py`

**Comment by rmcgibbo** [comment]
The purpose of the `msmbuilder/apm/reader_.py` is also not clear to me. This seems like an unrelated feature, and might be better off in a separate pull request.

**Comment by rmcgibbo** [comment]
And I am not convinced that the `plot_.py` file should be included in this PR. This does not seem sufficiently general-purpose, and more suited to your particular use case.

**Comment by rmcgibbo** [comment]
If you get a chance, the test failures (click on the "details" link from the PR page) show the error messages that you'll probably want to clean up.

**Comment by stephenliu1989** [comment]
Thank you Robert, I am checking the details from the PR pages.

**Comment by stephenliu1989** [comment]
Hi Robert, the code passed the checks.

**Comment by rmcgibbo** [comment]
Cool. I think the last major thing is probably adding some tests.

**Comment by stephenliu1989** [comment]
@rmcgibbo I have a test for APM in "/tests/test_apm" folder, is that test OK?

**Comment by rmcgibbo** [comment]
Take a look at some of the others tests for example, like https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/tests/test_msm.py.

**Comment by stephenliu1989** [comment]
thx for your example

2016年2月5日星期五，Robert T. McGibbon <notifications@github.com> 写道：

> Take a look at some of the others tests for example, like
> https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/tests/test_msm.py
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/msmbuilder/msmbuilder/pull/703#issuecomment-180231767>
> .
>


-- 
Best Wishes,
Stephen

**Comment by rmcgibbo** [comment]
To be clear, you don't necessarily need to follow exactly that example -- there are a lot of tests in https://github.com/msmbuilder/msmbuilder/tree/master/msmbuilder/tests. And of those could be useful examples. The general point is that you want to do some [unit testing](https://www.jeffknupp.com/blog/2013/12/09/improve-your-python-understanding-unit-testing/).

**Comment by stephenliu1989** [comment]
Dear @Robert, the APM with unit tests has updated

**Comment by mpharrigan** [comment]
It looks like you changed the file mode of every file. Can you undo that and [squash your commits](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/)

**Pull request closed without merging**
