### PR TITLE
added new decomp methods

### PR DESCRIPTION
**Pull request by cxhernandez**
- [x] Implement feature / fix bug
 - [ ] Add tests
 - [x] Update changelog

Adding `FastICA`, `FactorAnalysis`, `KernelPCA`. I didn't think `NMF` was that useful— sorry @msultan...

### CODE REVIEW

**Comment by cxhernandez** [comment]
Not sure while `n_components` [doesn't seem to get passed correctly](https://travis-ci.org/msmbuilder/msmbuilder/jobs/138748536#L6230) in the `KernelTICA` object....

**Comment by mpharrigan** [comment]
I'll merge this by hand because github says conflicts

**Comment by mpharrigan** [comment]
merged via rebased commits
64e19bb07970980554a0d46a4100ba41acd3058f
0f52fb832a360f5d8077c18f283d8a63815bcff2
785efe232e908dbfc0c4384087bc95d4280b573f

**Comment by cxhernandez** [comment]
I guess I'll add tests in another PR

**Pull request closed without merging**
