### PR TITLE
describe features for a list of featurizers

### PR DESCRIPTION
**Pull request by msultan**
- [x] Implement feature / fix bug
 - [x] Add tests
 - [ ] Update changelog

Added ability to describe features for the featureselector module. Works well for some of my stuff.

### CODE REVIEW

**Comment by cxhernandez** [comment]
+1

**Comment by mpharrigan** [comment]
Wanna add a simple test?

**Comment by msultan** [comment]
added one, it was surprisingly annoying to compare the equivalence of two pandas data frames where the types were changing along

**Comment by msultan** [comment]
one thing that i havent figured out is how to handle featurizers which dont have ```describe_features```. right now it will raise an error when we call it but a better option might be to add N/A to all the columns or something. 
a third option might be to add that as the default value for all featurizer objects by changing the base class featurizer class.

**Comment by cxhernandez** [comment]
+1 for returning `None` for missing feature descriptions

**Comment by mpharrigan** [comment]
What's the status of this?

**Comment by msultan** [comment]
missing the N/A for featurizers that dont have the describe_features attribute. i think i will have to change the featurizer object a bit for that to work properly. gimme a few hours today.

**Pull request closed without merging**
