### PR TITLE
Generalize kappa

### PR DESCRIPTION
**Pull request by msultan**
- [x] Implement feature / fix bug
 - [x] Add tests
 - [x] Update changelog

I wanted a CA based featurizer that was tunable, so i generalized the kappa angle featurizer to accept an offset keyword.

### CODE REVIEW

**Comment by msultan** [comment]
anyone know why conda seems to be broken?

**Comment by brookehus** [comment]
it might be neater to change `KappaAngleFeaturizer` so it is an instance of `AngleFeaturizer`

**Comment by cxhernandez** [comment]
still broken

**Comment by msultan** [comment]
Arrghh, its not listed in the command line .

**Pull request merged**
