### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by cxhernandez**
add py3.6 in testing #988

### CODE REVIEW

**Comment by mpharrigan** [comment]
Should we remove python 3.4? Should we add numpy 1.12?

**Comment by cxhernandez** [comment]
> Should we remove python 3.4?

Why 3.4 before 2.7?

> Should we add numpy 1.12?

👍

**Comment by mpharrigan** [comment]
The general idea is "latest two pythons plus python 2.7". I'm sure usage statistics would back this up as would amount of discussion #852

**Comment by cxhernandez** [comment]
Ah, got it. Should we look into implementing #852?

**Comment by mpharrigan** [comment]
Feel free to continue the discussion there.

Another point worth mentioning: if the code passes tests in python 3.5, it's likely it will also work in 3.4 whereas 2.7 is the last of its kind, and removing it isn't just a normal matter of business

**Pull request closed without merging**
