### PR TITLE
3.3-APM

### PR DESCRIPTION
**Pull request by stephenliu1989**
# Automatic State Partitioning for Multibody Systems (APM)
### 1. Introduction
This Program is a python package which implements Automatic State Partitioning for Multibody Systems (APM) algorithm to cluster trajectories and model the transitions based on a Markov State Model (MSM). 

### 2. System Requirement
- Python 2.7.10
- Numpy 1.9.2
- Scipy 0.15.1
- Scikit-learn 0.16.1
- Matplotlib 1.4.3
- MDTraj 1.3.0
- MSMBuilder 3.2.0

### 3. Documentation
The Doxygen documentation for this code can be found at [doc](http://chz382.ust.hk/doc/stephen/MSMB_APM/).

### 4. Install Python and Python Packages
We highly recommend that you download the Python 2.7 version of Anaconda, which is a completely free enterprise-ready Python distribution for large-scale data processing, predictive analytics, and scientific computing.

#### - 2D Potential
	cd test_2D_potential/
	python test_apm_2d.py 
	
***optional arguments:***
   	 	-h, --help            show this help message and exit
    	-t TRAJLISTFNS, --trajListFns TRAJLISTFNS
                          List of trajectory files to read in, separated by
                          spaces.
    	-a ATOMLISTFNS, --atomListFns ATOMLISTFNS
                          List of atom index files to read in, separated by
                          spaces.
    	-g TOPOLOGY, --topology TOPOLOGY
                          topology file.
    	-e IEXT, --iext IEXT  The file extension of input trajectory files. Must be
                          a filetype that mdtraj.load() can recognize.
    	-s STRIDE, --stride STRIDE
                          stride.
    	-m N_MACROSTATES, --n_macrostates N_MACROSTATES
                          n_macrostates.
    	-l LAG_TIME, --lag_time LAG_TIME
                          lag_time.
    	-i MAX_ITER, --max_iter MAX_ITER
                          max_iter.
    	-c SUB_CLUSTER, --sub_cluster SUB_CLUSTER
                          sub_cluster.  
#### - Alanine Dipeptide
		cd test_ala/
		python test_apm_ala.py

#### References
**Fu Kit SHEONG, …, Xuhui HUANG**, [“Automatic State Partitioning for Multibody Systems (APM): An Efficient Algorithm for Constructing Markov State Models To Elucidate Conformational Dynamics of Multibody Systems”](http://pubs.acs.org/doi/abs/10.1021/ct5007168), **J. Chem. Theory Comput., 2015, 11 (1), pp 17–27**

#### Credits:
**Code Author:** [LIU Song](http://chz382.ust.hk/u/stephen): *stephenliu1989@gmail.com*
**Contributors:** Fukit SHEONG, Xuhui HUANG
Copyright (c) 2015, Hong Kong University of Science and Technology (HKUST)
Source Code:
[apm-src.zip](https://github.com/msmbuilder/msmbuilder/files/91402/apm-src.zip)

### CODE REVIEW

**Comment by stephenliu1989** [comment]
[apm-src.zip](https://github.com/msmbuilder/msmbuilder/files/91401/apm-src.zip)

**Comment by rmcgibbo** [comment]
Hi @stephenliu1989!

This will be a great feature to have. Generally the way that we incorporate new code is through `git`, the version control system that we use here with Github.com. The workflow we use is with Pull Requests. There is some [documentation](https://help.github.com/articles/using-pull-requests/)  and [tutorials](https://yangsu.github.io/pull-request-tutorial/) on the web that might be useful, or I can walk though the system with you.

**Comment by stephenliu1989** [comment]
Hi Robert,
Thanks for your instructions! I will follow the tutorials.

2016-01-15 14:03 GMT+08:00 Robert T. McGibbon <notifications@github.com>:

> Hi @stephenliu1989 <https://github.com/stephenliu1989>!
>
> This will be a great feature to have. Generally the way that we
> incorporate new code is through git, the version control system that we
> use here with Github.com. The workflow we use is with Pull Requests. There
> is some documentation
> <https://help.github.com/articles/using-pull-requests/> and tutorials
> <https://yangsu.github.io/pull-request-tutorial/> on the web that might
> be useful, or I can walk though the system with you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/msmbuilder/msmbuilder/pull/702#issuecomment-171879595>
> .
>



-- 
Best Wishes,
Stephen

**Comment by mpharrigan** [comment]
See #703

**Pull request closed without merging**
