### PR TITLE
Correct indentation level in describe_features

### PR DESCRIPTION
**Pull request by msultan**
- [x] Implement feature / fix bug
 - [x ] Add tests
 - [ ] Update changelog

I have no idea how the dataframe was been returned when the function had extra tabs in it.

### CODE REVIEW

**Comment by brookehus** [comment]
interesting

**Comment by mpharrigan** [comment]
Is it actually tabs or is it just indented too far? I think python will accept it if it's at least consistent indentation

**Comment by mpharrigan** [comment]
```python
def f(x):
    z = x**2
    return z

def g(x):
        z = x**3
        return z
    
def h(x):
    z = x**3
     return z # IndentationError
```

**Comment by msultan** [comment]
i am not really sure. it just kept doing weird things on my mac and seems to have been fixed now.

**Pull request merged**
