### PR TITLE
port sklearn preprocessing

### PR DESCRIPTION
**Pull request by cxhernandez**
- [x] Implement feature / fix bug
 - [x] Add tests
 - [x] Update changelog

re: https://github.com/msmbuilder/msmbuilder/pull/770#issuecomment-207139793

### CODE REVIEW

**Comment by cxhernandez** [comment]
I couldn't get `LabelEncoder` or `OneHotEncoder` to work properly. I'm not sure they're that useful for our purposed though....

**Comment by cxhernandez** [comment]
@mpharrigan: any idea how to fix py34?

**Comment by cxhernandez** [comment]
Might have to make two versions of `MinMaxScaler` and `StandardScaler`, since `partial_fit` was not implemented in these until sklearn v0.17. Should I call the newer ones `MinMaxOnlineScaler` and  `StandardOnlineScaler`?

**Comment by mpharrigan** [comment]
> Might have to make two versions of MinMaxScaler and StandardScaler, since partial_fit was not implemented in these until sklearn v0.17. Should I call the newer ones MinMaxOnlineScaler and StandardOnlineScaler along with a deprecation warning?

-1 from me. Can we just use the new one and give a helpful error message if someone tries to use it with insufficient scipy

**Comment by mpharrigan** [comment]
Also this pr is fantastic! Thanks for doing this

**Comment by cxhernandez** [comment]
I'm just putting in conditionals so that if it doesn't exist in sklearn, the class won't be generated. Hopefully by the time msmb v3.5 is out, sklearn v0.17 is available for all platforms.

**Comment by cxhernandez** [comment]
@mpharrigan: approval to merge?

**Comment by mpharrigan** [comment]
Looks great from my end. I'm going to turn off the required status checks so you can merge

**Comment by mpharrigan** [comment]
Actually I'm not going to do that because they added an option to turn off the requirement that the branch be up to date, which was my huge gripe. I'm going to leave the ci requirements (for now) such that we are motivated to fix the random test failures

**Comment by cxhernandez** [comment]
> motivated to fix the random test failures

😞

**Pull request merged**
