### PR TITLE
Added Slicer transformer

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
If there is a better way to do this, let me know.  This might already be a thing somewhere...

```
import msmbuilder.featurizer

X = [np.random.normal(size=(100, 5), loc=np.arange(5))] + [np.random.normal(size=(10, 5), loc=np.arange(5))]

slicer = msmbuilder.featurizer.Slicer(index=[0, 1])

Y = slicer.transform(X)
len(Y)
Y[0].shape

slicer = msmbuilder.featurizer.Slicer(first=3)

Y = slicer.transform(X)
len(Y)
Y[0].shape

In [5]: len(Y)
Out[5]: 2

In [6]: Y[0].shape
Out[6]: (100, 2)

In [9]: len(Y)
Out[9]: 2

In [10]: Y[0].shape
Out[10]: (100, 3)



```

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
PS: one of the reasons for this was to programmatically control the `n_components` parameter in tICA without re-doing the calculation.

**Comment by mpharrigan** [comment]
I've hacked together something like this in my own uses (for tica), so I can see the utility

**Comment by rmcgibbo** [comment]
This looks good to me, except that I don't really understand the docstrings.

**Comment by kyleabeauchamp** [comment]
Cool, I'll add tests and docstrings.

**Comment by kyleabeauchamp** [comment]
OK, so I split this into two subclasses: `Slicer` and `FirstSlicer`, where FirstSlicer takes an integer as input.  

I did this because I'm uncomfortable with having multiple "interdependent" hyperparameters in the constructor.  I imagine it could be done properly, but I imagine lots of corner cases.

**Comment by rmcgibbo** [comment]
Why do these inherit from featurizer?

**Comment by kyleabeauchamp** [comment]
To borrow the `partial_fit()` function

**Comment by kyleabeauchamp** [comment]
Still debugging this, there's some sequence shape issue that I'm only seeing when executed via osprey:

```

    eval: |
        Pipeline([
                ("slicer", FirstSlicer()),
                ("gmm", KMeans())
        ])

------------------------------------------------------------------------------
Exception encountered while fitting model
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kyleb/opt/lib/python2.7/site-packages/osprey-0.4_25_gd72f720_dirty-py2.7.egg/osprey/execute_worker.py", line 121, in run_single_trial
    estimator, params, cv=cv, scoring=scoring, X=X, y=y, verbose=1)
  File "/home/kyleb/opt/lib/python2.7/site-packages/osprey-0.4_25_gd72f720_dirty-py2.7.egg/osprey/fit_estimator.py", line 60, in fit_and_score_estimator
    for train, test in cv)
  File "/home/kyleb/opt/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 659, in __call__
    self.dispatch(function, args, kwargs)
  File "/home/kyleb/opt/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 406, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/home/kyleb/opt/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 140, in __init__
    self.results = func(*args, **kwargs)
  File "/home/kyleb/opt/lib/python2.7/site-packages/osprey-0.4_25_gd72f720_dirty-py2.7.egg/osprey/fit_estimator.py", line 119, in _fit_and_score
    test_score = _score(estimator, X_test, y_test, scorer)
  File "/home/kyleb/opt/lib/python2.7/site-packages/sklearn/cross_validation.py", line 1532, in _score
    score = scorer(estimator, X_test)
  File "/home/kyleb/opt/lib/python2.7/site-packages/sklearn/metrics/scorer.py", line 201, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/home/kyleb/opt/lib/python2.7/site-packages/sklearn/utils/metaestimators.py", line 37, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "/home/kyleb/opt/lib/python2.7/site-packages/sklearn/pipeline.py", line 289, in score
    return self.steps[-1][-1].score(Xt, y)
  File "/home/kyleb/opt/lib/python2.7/site-packages/sklearn/cluster/k_means_.py", line 881, in score
    X = self._check_test_data(X)
  File "/home/kyleb/opt/lib/python2.7/site-packages/sklearn/cluster/k_means_.py", line 762, in _check_test_data
    X = check_array(X, accept_sparse='csr')
  File "/home/kyleb/opt/lib/python2.7/site-packages/sklearn/utils/validation.py", line 341, in check_array
    array = np.array(array, dtype=dtype, order=order, copy=copy)
ValueError: setting an array element with a sequence.



```

**Comment by kyleabeauchamp** [comment]
Oops, might be my bad there.

**Comment by kyleabeauchamp** [comment]
OK, I think we're OK, I've got a Slicer -> GMM -> MSM working in osprey.

**Pull request merged**
