### PR TITLE
ENH: Split cluster_ids_ in *KMedoids

### PR DESCRIPTION
**Pull request by mpharrigan**
cc #514

### CODE REVIEW

**Comment by rmcgibbo** [comment]
can you make sure in the test that this works when the input trajectories are not the same length?

**Comment by mpharrigan** [comment]
Good point

**Comment by mpharrigan** [comment]
Tests updated. Also seems to work on my actual dataset

**Comment by rmcgibbo** [comment]
Is there any way to make the test actually exact though?

**Comment by rmcgibbo** [comment]
like, check that the referenced cluster centers, in coordinate space, are equal to `X[_KMedoids().fit(X).cluster_ids_]`?

**Comment by mpharrigan** [comment]
Oh yeah that would be better

**Comment by mpharrigan** [comment]
Travis failure is an http timeout

**Pull request merged**
