### PR TITLE
cleaned up repititive code in bayes and msm

### PR DESCRIPTION
**Pull request by msultan**
Cleaned up bayes and regular msm fit code and moved it to a superclass #710. We could probably merge the eigensystem solver too if we add a few hidden attributes to the the regular msm class.

### CODE REVIEW

**Comment by mpharrigan** [comment]
Tests are hanging. overall +1 on the idea of this pr so long as it's bug free

**Comment by msultan** [comment]
test_msm was passing locally but lets wait on travis to finish all tests.

**Comment by msultan** [comment]
@mpharrigan travis is passing now.

**Comment by cxhernandez** [comment]
yayyy

**Pull request merged**
