### PR TITLE
Add sasa describe (again)

### PR DESCRIPTION
**Pull request by nhstanley**
- [x] Implement feature / fix bug
 - [x] Add tests
 - [x] Update changelog

I added this last year but the functionality needed wasn't merged into or distributed with common versions of MDTraj yet. That should no longer be an issue.

### CODE REVIEW

**Comment by nhstanley** [comment]
Looks like the appveyor failed because the build specifies MDTraj v 1.8 or less, but this feature wasn't incorporated until 1.9. Is it ok to update the requirement?

**Comment by cxhernandez** [comment]
Might have to make a new PR to incorporate mdtraj v1.9. IRCC, v1.9 was breaking some tests.

**Comment by cxhernandez** [comment]
@brookehus: why did you merge this? #1052 is still blocking

**Comment by brookehus** [comment]
My bad, feel free to revert.

**Pull request merged**
