### PR TITLE
New implement describe

### PR DESCRIPTION
**Pull request by msultan**
- [x] Implement feature / fix bug
 - [x] Add tests
 - [ ] Update changelog

new decribe_features for the FeatureSelector module mostly because I dont know how to git and this was faster. replaces #812

### CODE REVIEW

**Comment by msultan** [comment]
wtf is going on.

**Comment by mpharrigan** [comment]
> wtf is going on. 

For those following along at home, @msultan did a rebase and now all is well :)

**Comment by brookehus** [comment]
Phew, I was on the edge of my seat

**Comment by cxhernandez** [comment]
Yayyyyy

**Comment by msultan** [comment]
thank you @mpharrigan for all the help with the magic that is rebase.

**Comment by msultan** [comment]
@brookehus your sarcasm has been noted and cataloged for future reference.

**Pull request merged**
