### PR TITLE
Clean up describe_features

### PR DESCRIPTION
**Pull request by mpharrigan**
cc #675

### CODE REVIEW

**Comment by mpharrigan** [comment]
@msultan can you look at this, check it still works, think of a test we can add

**Comment by msultan** [comment]
The ```set``` logic doesn't work if you have two or more of the same type of residues in a row and you are iterating over the atom indices. 

```python
In [34]: df[509:510]
Out[34]: 
                     atominds  featuregroup featurizer           resids  \
509  [3975, 3977, 3988, 3990]  nosincos-psi   Dihedral  set([248, 247])   

       resnames          resseqs  
509  set([GLU])  set([248, 249])  

```
Since we are changing this, would changing resids to residue_index make more sense?

**Comment by mpharrigan** [comment]
Why do you want only unique resids and resseqs but all the resnames

**Comment by msultan** [comment]
seems more consistent imho.

**Comment by mpharrigan** [comment]
> Why do you want only unique resids and resseqs but all the resnames

This is the opposite of consistent. Would you be ok with returning a four-tuple for each relevant field?

**Comment by msultan** [comment]
I thought about this more. I think the unique implementation makes more sense. If a user wants more detail, they can iterate over the atom indices then. 
Good to merge imo.

**Comment by mpharrigan** [comment]
Wait, I think I just figured out what you may have actually been saying instead of what I thought you were saying. 

You want the four atom indices and info on the residues to which they belong. i.e. unique resids and for each unique resid, the associated resseq and resname. You could use this info to color residues in vmd or something

**Comment by msultan** [comment]
Ya thought the unique resid/resSeq is already there so I think we are fine. I was worried about the resname but I think its okay to keep that unique as well for consistency. 
Also what do you think about adding ```chain id``` ? Might be useful in multiprotein systems or membrane proteins with missing loops.

**Comment by msultan** [comment]
@mpharrigan do you wanna merge this and I can use the pattern to fix the ```describe_features``` for other featurizers too?

**Comment by mpharrigan** [comment]
Let me fix it to do what you actually wanted it to do re: Number of resseq entries

**Comment by mpharrigan** [comment]
@msultan can you check the latest version of this. It will find unique resids and give the resids, resnames, and resseq all as lists of length(number of unique residues)

**Comment by cxhernandez** [comment]
also add a test for https://github.com/msmbuilder/msmbuilder/issues/739

**Comment by msultan** [comment]
gonna do this tomorrow. sry for being awol all day, i was trying to find the damn h264 codec on my mac

**Comment by msultan** [comment]
also, should we fix the other ```describe_feature``` attributes as well?

**Comment by mpharrigan** [comment]
Can you do that?

**Pull request closed without merging**
