### PR TITLE
Added pickle output for featurizer command line.

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
Addresses #392 and  #542.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
I have no preference for whether or not this makes the current release, but it might be worth discussing as it does change some command line API arguments.

**Comment by mpharrigan** [comment]
generally +1

The responsible thing to do may be to deprecate `--out` with this release and introduce `--transformed`, and then change the behavior of `--out` in 3.3.

**Comment by kyleabeauchamp** [comment]
Sounds good to me--so we'll just add a deprecation note in the helpstring --out for 3.2 and then pull the trigger for 3.3.

**Comment by mpharrigan** [comment]
Do you want to file a PR for that?

**Comment by kyleabeauchamp** [comment]
Cool, looks like travis passes here.  Obviously this can wait until the dust settles for the current release.

**Comment by mpharrigan** [comment]
Cool. Do you want to just delete the deprecation test?

**Comment by kyleabeauchamp** [comment]
Done

**Comment by kyleabeauchamp** [comment]
PS: I suppose this is ready to merge, although I'm happy to wait until after the GHMM stuff is finished.

**Comment by rmcgibbo** [comment]
Kk.

**Pull request merged**
