### PR TITLE
Use Travis "deploy" infrastructure

### PR DESCRIPTION
**Pull request by mpharrigan**

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Did you remove the binstar token part?

**Comment by mpharrigan** [comment]
Good spot. 

I'm going to push a couple more commits, and merge this to see if deploying happens (it will upload to msmbuilder.org/test-deploy)

I need to figure out how to encode the logic of "if not release, put in latest/ otherwise put in releasename/"

**Comment by mpharrigan** [comment]
merging this, fingers crossed

**Comment by mpharrigan** [comment]
I'm gonna start committing to master to get this working, sorry in advance

**Comment by mpharrigan** [comment]
This is now working after many commits to master. Still to-do:
 - reenable running tests
 - reenable building example notebooks
 - [for next release!] check that generating and uploading versions.json works

**Pull request merged**
