### PR TITLE
Update install_miniconda.sh

### PR DESCRIPTION
**Pull request by cxhernandez**
re: https://github.com/msmbuilder/msmbuilder/issues/932

### CODE REVIEW

**Comment by msultan** [comment]
can we push this PR yet? I think its holding up #936

**Comment by cxhernandez** [comment]
@mpharrigan has the keys

**Comment by jchodera** [comment]
Anaconda finally fixed the md5 hash issue, so things should be working again with this change.

**Comment by mpharrigan** [comment]
You guys cant merge things?

**Comment by cxhernandez** [comment]
@mpharrigan: not when appveyor fails/stalls 😕

**Pull request merged**
