### PR TITLE
Small modifications to command line tutorial

### PR DESCRIPTION
**Pull request by mpharrigan**
cc #485 

 - Changed the title to be more obvious that it is a tutorial
 - Small fixes to filenames to correspond to use of "datasets"

### CODE REVIEW

**Comment by rmcgibbo** [comment]
We should consider making command line tutorials in the form of IPython notebooks that use a bash backend. https://github.com/takluyver/bash_kernel

**Comment by mpharrigan** [comment]
Ipython bash backend would be a long term thing. That requires ipy 3 (not released yet)

**Comment by rmcgibbo** [comment]
I think it's going to be released this week. Not for immediate use, yes, but something like that might be a nice tool for tutorials that involve showing command line code, in the way that the ipython notebook is nice for tutorials that involve showing people python code.

**Comment by rmcgibbo** [comment]
I got the bash kernel working with `pip install --pre ipython`, which gives 3.0.0rc1.

See e.g.

http://nbviewer.ipython.org/gist/rmcgibbo/d80b21971909799952f6

**Comment by mpharrigan** [comment]
Is bash kernel included with ipy3?

**Comment by rmcgibbo** [comment]
No, need to install it separately. But most users will just by copy-pasting, not actually downloading and running the .ipynb files I would guess.

**Comment by kyleabeauchamp** [comment]
I'll leave it up to you guys to decide whether this will be easy to maintain given the pre-release status of the two prerequisites.

**Comment by rmcgibbo** [comment]
We don't need to do this now. It's just something to watch out for going forward.

**Comment by zjlhjun** [comment]
Yes, I think the tutorial is very important. Following the examples, we will learn it very fast. But, I can not find the tutorial in the version 3.1.

**Pull request merged**
