### PR TITLE
project templates build fix

### PR DESCRIPTION
**Pull request by brookehus**
- [x] Implement feature / fix bug
 - [ ] Add tests
 - [ ] Update changelog

Solves my issue #881 but not sure if this is a good fix.

### CODE REVIEW

**Comment by brookehus** [comment]
@mpharrigan, @cxhernandez, @msultan, all of whom I bothered about this to varying extents

**Comment by cxhernandez** [comment]
Interesting! It's weird to me that you'd need to specify a wildcard for a file extension, but I guess `setup.py` works in mysterious ways....

**Comment by mpharrigan** [comment]
I'm curious why it wasn't working for you, but seemed to be working on travis. Maybe a mac thing?

**Comment by brookehus** [comment]
Not sure, because my initial problem was when I tried to install the latest msmb on biox3.

**Comment by mpharrigan** [comment]
Do you want to investigate? Try different versions of python or setuptools?

**Comment by brookehus** [comment]
Maybe a python 2.7 thing. I started from scratch on Sherlock. When I have 

```
(p3)[bhusic@sherlock-ln03:~/source/msmbuilder (master)]$ python -V
Python 3.5.2 :: Continuum Analytics, Inc.
```

the build works fine. On the other hand,

```
[bhusic@sherlock-ln03:~/source/msmbuilder (master)]$ python -V
Python 2.7.11 :: Continuum Analytics, Inc.
[bhusic@sherlock-ln03:~/source/msmbuilder (master)]$ python setup.py install
C compiler:
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) 
Attempting to autodetect OpenMP support... Compiler supports OpenMP
Attempting to autodetect SSE3   support... Compiler supports SSE3
Attempting to autodetect SSE4.1 support... Compiler supports SSE4.1

running install
running bdist_egg
running egg_info
writing msmbuilder.egg-info/PKG-INFO
writing top-level names to msmbuilder.egg-info/top_level.txt
writing dependency_links to msmbuilder.egg-info/dependency_links.txt
writing entry points to msmbuilder.egg-info/entry_points.txt
reading manifest file 'msmbuilder.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'msmbuilder.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying msmbuilder/version.py -> build/lib.linux-x86_64-2.7/msmbuilder
error: can't copy 'msmbuilder/project_templates/msm': doesn't exist or not a regular file
```

**Comment by brookehus** [comment]
The branch I'm PRing here works for both.

**Comment by mpharrigan** [comment]
https://github.com/pypa/setuptools/issues/261

fixed in setuptools v21.2.1

python version is a :red_circle: :fish:

**Comment by msultan** [comment]
> 🔴 🐟 

red ball fish? 

glad to know this got figured out though.

**Pull request merged**
