### PR TITLE
Be aggressive against argspec deprecation warnings

### PR DESCRIPTION
**Pull request by mpharrigan**

### CODE REVIEW

**Comment by rmcgibbo** [comment]
This is actually hilarious.

**Comment by msultan** [comment]
maybe email the warnings as text to argspec's owners.

**Comment by rmcgibbo** [comment]
Well, once Anaconda updates their packages to the latest releases, it'll stop being a problem. It's already been fixed upstream.

**Comment by mpharrigan** [comment]
It would also help if sklearn didn't force warnings to "on" with no way to turn it off

**Comment by rmcgibbo** [comment]
Where in the sklearn code is that done?

**Comment by mpharrigan** [comment]
Ok, I don't think sklearn does it anymore but something in msmbuilder/mdtraj is turning warnings on!

```python
>>> import warnings
>>> warnings.warn("hi", DeprecationWarning)
>>> import mdtraj
>>> warnings.warn("hi", DeprecationWarning)
__main__:1: DeprecationWarning: hi
```

Run the above from not-ipython (which also fiddles with default warnings)

**Comment by mpharrigan** [comment]
@rmcgibbo !! for shame

https://github.com/mdtraj/mdtraj/blob/master/mdtraj/utils/__init__.py#L22

**Comment by mpharrigan** [comment]
This shouldn't be necessary with new mdtraj release

**Pull request closed without merging**
