### PR TITLE
Holmes-Rubin rate matrix EM algorithm

### PR DESCRIPTION
**Pull request by rmcgibbo**
This PR implements an alternative method for fitting the rate matrix models using EM. The algorithm is described in [1] and reviewed in [2], (where it's called the "Enhanced MLE-method for the reversible case"). I used the description and notation in [2] as the basis of the implementation.

The method is not wrapped an estimator class, and does not follow the estimator class API.

My reason for implementing it is not really to add a new feature to MSMBuilder. What I really want to do is compare the performance and accuracy of the estimator used by `ContinuousTimeMSM` to the Holmes-Rubin estimator for my paper [3], and I could not find a suitable existing implementation of the Holmes-Rubin estimator.

[1] Holmes, I., and G. M. Rubin. "An expectation maximization algorithm for training hidden substitution models." J. Mol. Biol. 317.5 (2002): 753-764.
[2] Metzner, Philipp, et al. "Generator estimation of Markov jump processes." J. Comp. Phys. 227.1 (2007): 353-375.
[3] http://arxiv.org/abs/1504.01804

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Perhaps I will make a new repository for this -- it's not really appropriate for MSMBuilder.

**Comment by kyleabeauchamp** [comment]
Im fine either way

**Comment by mpharrigan** [comment]
I'd suggest either a different repository or an unmerged branch

**Comment by rmcgibbo** [comment]
I moved the code to https://github.com/rmcgibbo/holmes_rubin

**Pull request closed without merging**
