### PR TITLE
Allow appending to datasets

### PR DESCRIPTION
**Pull request by mpharrigan**
At least for `dir-npy`

### CODE REVIEW

**Comment by rmcgibbo** [comment]
test?

**Comment by mpharrigan** [comment]
added a test

**Comment by mpharrigan** [comment]
P.S. my use case for this is featurizing in parallel

**Comment by rmcgibbo** [comment]
in the test: what about appending to one of the values associated with a
key that's already in the dataset?

On Mon, Mar 23, 2015 at 11:13 AM, Matthew Harrigan <notifications@github.com

**Comment by mpharrigan** [comment]
What's the expected behavior? I'd think overwrite

**Comment by kyleabeauchamp** [comment]
Unrelated question: are you using this functionality via the command line or via python?  I'm mostly just curious whether I should be trying to emulate your workflows here, but there's not so much in terms of "idiom" examples in the docs.

**Comment by mpharrigan** [comment]
Right now I'm doing it via IPython.parallel. And featurizing many microseconds in < 2 minutes

**Comment by kyleabeauchamp** [comment]
Thanks, good to know.

**Comment by rmcgibbo** [comment]
> What's the expected behavior?

I'm not sure. I figured that we should probably decide though.

**Comment by mpharrigan** [comment]
With `w` it's been overwrite

**Comment by rmcgibbo** [comment]
Okay. Looks good. the docstrings mention this.

**Comment by mpharrigan** [comment]
Gah py2 issues

**Pull request merged**
