### PR TITLE
Fix test failures

### PR DESCRIPTION
**Pull request by cxhernandez**

### CODE REVIEW

**Comment by mpharrigan** [comment]
There are still several preprocessing and "mad" failures

**Comment by mpharrigan** [comment]
(in addition to decomposition and tpt failures)

**Comment by mpharrigan** [comment]
This means #858 won't get built. Please hurry with fixing these tests

**Comment by mpharrigan** [comment]
bump

**Comment by cxhernandez** [comment]
Gonna try to fix these today!

**Comment by mpharrigan** [comment]
Also blocking #862

**Comment by cxhernandez** [comment]
Okay, I'm hoping this works 🍀

**Comment by cxhernandez** [comment]
bump @mpharrigan

**Comment by mpharrigan** [comment]
Thanks!

**Pull request merged**
