### PR TITLE
added atom indices to dihedral featurizer and kappa featurizer 

### PR DESCRIPTION
**Pull request by msultan**
Changed the dihedral and kappa featurizers to save atom indices used. This somewhat implements  https://github.com/msmbuilder/msmbuilder/issues/448 . I welcome any other ways in which this might be done.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Yeah, the only ideas I had was either this or creating a separate object that duplicates the code in DihedralFeaturizer but without actually outputting the trajectories.  Something like below, which I'm only including to keep a record of this.

```
def describe_features(self, traj):
    """Return a Pandas Dataframe describing the features."""
    x = []
    for a in self.types:
        func = getattr(md, 'compute_%s' % a)
        aind, y = func(traj)
        n = len(aind)
        
        aind = aind[:, 1]
        
        resnames = [traj.top.atom(i).residue.name for i in aind]
        resSeq = [traj.top.atom(i).residue.resSeq for i in aind]
        resid = [traj.top.atom(i).residue.index for i in aind]
        bigclass = ["dihedral"] * n
        smallclass = [a] * n
        
        if self.sincos:
            #x.extend([np.sin(y), np.cos(y)])
            resnames = resnames * 2
            resSeq = resSeq * 2
            resid = resid * 2
            trig = (["sin"] * n) + (["cos"] * n)
            bigclass = bigclass * 2
            smallclass = smallclass * 2
        else:
            trig = ["nosincos"] * n
        
        for i in range(len(resnames)):
            d_i = dict(resname=resnames[i], resSeq=resSeq[i], resid=resid[i], trig=trig[i], bigclass=bigclass[i], smallclass=smallclass[i])
            x.append(d_i)
    
    return x

**Comment by msultan** [comment]
I think pandas df might be a better idea than my array of arrays though I think saving residue information is problematic since many features involve multiple residues. I was thinking we save the information at the atom level and then combine that to get residue level information.

**Comment by msultan** [comment]
So I had a conversation with @mpharrigan  and @rmcgibbo about this offline. Matt thinks we should have a separate method which is topology dependent so it makes sense to use something akin to what kyle suggested above.

**Comment by msultan** [comment]
Gonna close this and continue conversation in https://github.com/msmbuilder/msmbuilder/issues/448 since this requires a little more thought

**Pull request closed without merging**
