### PR TITLE
Test to make sure things show up on commandline

### PR DESCRIPTION
**Pull request by mpharrigan**
This set of autogenerated tests looks for things that get imported
in the msmbuilder subpackages (`msmbuilder.featurizer` , `.msm`,
`.decomposition`, etc) and tries to figure out whether there are classes
that probably should be exposed on the command line.

The tests test whether they're actually exposed on the command line.

The 'auto discovery' process isn't flawless, and you can manually
include or exclude classes from consideration. If there is a lot of
garbage being imported into these top level namespaces, I think we
really should consider fixing the root of the problem (don't import `*`)
rather than going crazy with the "exclude" section.

### CODE REVIEW

**Comment by mpharrigan** [comment]
cc #733 

@brookehus : you can make a new branch off of my branch to actually fix the problems (I can show you how to do this)

**Comment by mpharrigan** [comment]
Local test results
```
test_msmbuilder.featurizer.SubsetFeatureUnion_listed ... FAIL
test_msmbuilder.featurizer.SuperposeFeaturizer_listed ... ok
test_msmbuilder.featurizer.DRIDFeaturizer_listed ... ok
test_msmbuilder.featurizer.KappaAngleFeaturizer_listed ... ok
test_msmbuilder.featurizer.SubsetCosPsiFeaturizer_listed ... FAIL
test_msmbuilder.featurizer.TrajFeatureUnion_listed ... FAIL
test_msmbuilder.featurizer.FirstSlicer_listed ... FAIL
test_msmbuilder.featurizer.FunctionFeaturizer_listed ... FAIL
test_msmbuilder.featurizer.SubsetAtomPairs_listed ... FAIL
test_msmbuilder.featurizer.AtomPairsFeaturizer_listed ... ok
test_msmbuilder.featurizer.ContactFeaturizer_listed ... ok
test_msmbuilder.featurizer.FeatureUnion_listed ... FAIL
test_msmbuilder.featurizer.SubsetSinPhiFeaturizer_listed ... FAIL
test_msmbuilder.featurizer.StrucRMSDFeaturizer_listed ... ok
test_msmbuilder.featurizer.Slicer_listed ... FAIL
test_msmbuilder.featurizer.GaussianSolventFeaturizer_listed ... ok
test_msmbuilder.featurizer.SASAFeaturizer_listed ... FAIL
test_msmbuilder.featurizer.SubsetCosPhiFeaturizer_listed ... FAIL
test_msmbuilder.featurizer.RawPositionsFeaturizer_listed ... FAIL
test_msmbuilder.featurizer.AlphaAngleFeaturizer_listed ... ok
test_msmbuilder.featurizer.DummyCV_listed ... FAIL
test_msmbuilder.featurizer.SubsetTrigFeaturizer_listed ... FAIL
test_msmbuilder.featurizer.SubsetSinPsiFeaturizer_listed ... FAIL
test_msmbuilder.featurizer.DihedralFeaturizer_listed ... ok
test_msmbuilder.featurizer.RMSDFeaturizer_listed ... FAIL
test_msmbuilder.example_datasets.AlanineDipeptide_listed ... ok
test_msmbuilder.example_datasets.FsPeptide_listed ... ok
test_msmbuilder.example_datasets.MetEnkephalin_listed ... ok
test_msmbuilder.example_datasets.DoubleWell_listed ... ok
test_msmbuilder.example_datasets.MullerPotential_listed ... ok
test_msmbuilder.example_datasets.QuadWell_listed ... ok
test_msmbuilder.cluster.RegularSpatial_listed ... ok
test_msmbuilder.cluster.MeanShift_listed ... FAIL
test_msmbuilder.cluster.KMeans_listed ... ok
test_msmbuilder.cluster.KCenters_listed ... ok
test_msmbuilder.cluster.LandmarkAgglomerative_listed ... FAIL
test_msmbuilder.cluster.Ward_listed ... FAIL
test_msmbuilder.cluster.MiniBatchKMeans_listed ... ok
test_msmbuilder.cluster.GMM_listed ... FAIL
test_msmbuilder.cluster.KMedoids_listed ... ok
test_msmbuilder.cluster.NDGrid_listed ... FAIL
test_msmbuilder.cluster.MiniBatchKMedoids_listed ... ok
test_msmbuilder.cluster.AgglomerativeClustering_listed ... FAIL
test_msmbuilder.cluster.SpectralClustering_listed ... FAIL
test_msmbuilder.cluster.AffinityPropagation_listed ... FAIL
test_msmbuilder.decomposition.PCA_listed ... ok
test_msmbuilder.decomposition.SparseTICA_listed ... ok
test_msmbuilder.decomposition.tICA_listed ... ok
test_msmbuilder.msm.MarkovStateModel_listed ... ok
test_msmbuilder.msm.BayesianContinuousTimeMSM_listed ... FAIL
test_msmbuilder.msm.BayesianMarkovStateModel_listed ... ok
test_msmbuilder.msm.ContinuousTimeMSM_listed ... ok
```

**Comment by mpharrigan** [comment]
Failures
```
est_msmbuilder.featurizer.SubsetFeatureUnion_listed ... FAIL
test_msmbuilder.featurizer.SubsetCosPsiFeaturizer_listed ... FAIL
test_msmbuilder.featurizer.TrajFeatureUnion_listed ... FAIL
test_msmbuilder.featurizer.FirstSlicer_listed ... FAIL
test_msmbuilder.featurizer.FunctionFeaturizer_listed ... FAIL
test_msmbuilder.featurizer.SubsetAtomPairs_listed ... FAIL
test_msmbuilder.featurizer.FeatureUnion_listed ... FAIL
test_msmbuilder.featurizer.SubsetSinPhiFeaturizer_listed ... FAIL
test_msmbuilder.featurizer.Slicer_listed ... FAIL
test_msmbuilder.featurizer.SASAFeaturizer_listed ... FAIL
test_msmbuilder.featurizer.SubsetCosPhiFeaturizer_listed ... FAIL
test_msmbuilder.featurizer.RawPositionsFeaturizer_listed ... FAIL
test_msmbuilder.featurizer.DummyCV_listed ... FAIL
test_msmbuilder.featurizer.SubsetTrigFeaturizer_listed ... FAIL
test_msmbuilder.featurizer.SubsetSinPsiFeaturizer_listed ... FAIL
test_msmbuilder.featurizer.RMSDFeaturizer_listed ... FAIL
test_msmbuilder.cluster.MeanShift_listed ... FAIL
test_msmbuilder.cluster.LandmarkAgglomerative_listed ... FAIL
test_msmbuilder.cluster.Ward_listed ... FAIL
test_msmbuilder.cluster.GMM_listed ... FAIL
test_msmbuilder.cluster.NDGrid_listed ... FAIL
test_msmbuilder.cluster.AgglomerativeClustering_listed ... FAIL
test_msmbuilder.cluster.SpectralClustering_listed ... FAIL
test_msmbuilder.cluster.AffinityPropagation_listed ... FAIL
test_msmbuilder.msm.BayesianContinuousTimeMSM_listed ... FAIL
```

**Comment by mpharrigan** [comment]
Also see the TODOs in https://github.com/mpharrigan/mixtape/blob/command-line-test/msmbuilder/tests/test_commands_exist.py#L67

**Comment by brookehus** [comment]
@mpharrigan not everything that passes the test shows up in [commands/__init__.py](https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/commands/__init__.py). e.g. `GaussianSolventFeaturizer` isnt' in commands/__init__. However, it seems to be capable of running from the command line. Thoughts?

**Comment by mpharrigan** [comment]
@brookehus did you ever do anything with this?

**Comment by brookehus** [comment]
Done in #879

**Pull request closed without merging**
