### PR TITLE
Support forthcoming msmb_data package that just puts stuff in prefix/share

### PR DESCRIPTION
**Pull request by mpharrigan**

### CODE REVIEW

**Comment by mpharrigan** [comment]
cc #853 

The decomposition tests, tpt tests, preprocessing tests, and mad tests are all broken (locally)

@cxhernandez and @msultan : please fix these asap

**Comment by cxhernandez** [comment]
I'll take a look

**Comment by msultan** [comment]
i am confused as to what happened here. i thought msmb_data was working. why such a large code commit?

**Comment by cxhernandez** [comment]
> i am confused as to what happened here. i thought msmb_data was working. why such a large code commit?

@mpharrigan found that because `msmb_data` used MSMBuilder v3.5 as a dependency, Travis was running the wrong tests. He's since made the package just an archive of data (https://github.com/msmbuilder/msmb_data/pull/12) and this PR includes code to handle that.

**Pull request merged**
