### PR TITLE
Fix Badges

### PR DESCRIPTION
**Pull request by cxhernandez**
somehow spaces were added

### CODE REVIEW

**Comment by mpharrigan** [comment]
Good find (and very weird)

**Comment by cxhernandez** [comment]
I found this issue with msmexplorer and osprey too. I wonder if GitHub has been tinkering....

**Comment by mpharrigan** [comment]
That would be impossible, it would change the git hashes and break everything

**Comment by mpharrigan** [comment]
although they changed their markdown rendering code recently :) https://githubengineering.com/a-formal-spec-for-github-markdown/

**Pull request merged**
