### PR TITLE
Tidy tests

### LINKED ISSUE #612: Quiet tests
Tests shouldn't produce any stdout. In practice, they print out a lot of stuff

### PR DESCRIPTION
**Pull request by mpharrigan**
- make sure they're quiet
- violently supress argspec deprecation warnings
- shim around use of argspec in msmbuilder commandline thingy
- make test names more interesting than `test_1`

fixes #612

### CODE REVIEW

**Comment by rmcgibbo** [comment]
wow this is a lot. good work.

**Comment by mpharrigan** [comment]
Next step: actually make the tests pass :)

**Comment by mpharrigan** [comment]
Depends https://github.com/omnia-md/conda-recipes/pull/430

**Comment by msultan** [comment]
well done @mpharrigan ! Definitely agree on renaming the tests with more descriptive names.

**Comment by mpharrigan** [comment]
Lovin' that big green check

**Pull request merged**
