### PR TITLE
consistent ergodic cut off across bayes msm and msm 

### PR DESCRIPTION
**Pull request by msultan**
This PR makes the msm and bayesmsm ergodic cutoff scheme consistent.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Lgtm

**Comment by msultan** [comment]
wait 1 sec. i need to change 1 thing.

**Comment by msultan** [comment]
alright, it should be good to merge once tests are done.

**Comment by mpharrigan** [comment]
Thanks @msultan !

Looks like python is getting mad at your indentation

```
======================================================================

ERROR: Failure: IndentationError (unindent does not match any outer indentation level (test_msm.py, line 364))

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/miniconda3/envs/_test/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest

    raise self.exc_val.with_traceback(self.tb)

  File "/home/travis/miniconda3/envs/_test/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName

    addr.filename, addr.module)

  File "/home/travis/miniconda3/envs/_test/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath

    return self.importFromDir(dir_path, fqname)

  File "/home/travis/miniconda3/envs/_test/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir

    mod = load_module(part_fqname, fh, filename, desc)

  File "/home/travis/miniconda3/envs/_test/lib/python3.5/imp.py", line 234, in load_module

    return load_source(name, filename, file)

  File "/home/travis/miniconda3/envs/_test/lib/python3.5/imp.py", line 172, in load_source

    module = _load(spec)

  File "<frozen importlib._bootstrap>", line 693, in _load

  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 658, in exec_module

  File "<frozen importlib._bootstrap_external>", line 764, in get_code

  File "<frozen importlib._bootstrap_external>", line 724, in source_to_code

  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed

  File "/home/travis/miniconda3/envs/_test/lib/python3.5/site-packages/msmbuilder-3.4.0.dev0-py3.5-linux-x86_64.egg/msmbuilder/tests/test_msm.py", line 364

    for cut_off in [0.01, 'on', 'off']:

                                      ^

IndentationError: unindent does not match any outer indentation level
```

**Comment by rmcgibbo** [comment]
My new favorite tool: pip install yapf; yapf -i your-file.py

**Comment by msultan** [comment]
thanks for the catch @mpharrigan, @rmcgibbo . should be fixed now

**Comment by msultan** [comment]
btw, the ```_strongly_connected_subgraph``` is called differently for the msm and bayesian msm models. 

its 
```
_strongly_connected_subgraph(self.lag_time * raw_counts,
                                             ergodic_cutoff, self.verbose)
``` for the bayesian model 
and 
```
 self.countsmat_, mapping2, self.percent_retained_ = \
                _strongly_connected_subgraph(raw_counts, ergodic_cutoff,
                                             self.verbose)
``` for the msm model. 
Is that by design?

**Comment by msultan** [comment]
alright the py3.4 failure is on the libdistance code and i dont think its my fault. Feel free to take another look/merge when ready.

**Comment by rmcgibbo** [comment]
`msmbuilder.tests.test_libdistance.test_pdist_rmsd_2` cc @brookehus :)

**Comment by brookehus** [comment]
@rmcgibbo how can i test stuff on py3.4 if it works fine on my computer? also i didn't mess with that test because it's just pdist. maybe it's the weird indentation of line 149. happy to check it out if you can direct me wrt my initial question.

**Comment by rmcgibbo** [comment]
maybe it just fails randomly. or maybe the scritness of the test is too tight, numerically.

**Comment by rmcgibbo** [comment]
i doubt it's actually a difference between py34 and any other python version. more likely that it's just stochastic.

**Comment by brookehus** [comment]
could try changing the decimal parameter of assert_almost_equal

**Comment by rmcgibbo** [comment]
it looks to me like the error is coming from comparing the zeros, so it might be exactly this issue: https://github.com/mdtraj/mdtraj/issues/1006

**Comment by mpharrigan** [comment]
What's the status of this?

**Comment by rmcgibbo** [comment]
+1 to merge

**Pull request merged**
