### PR TITLE
Sampling along tica coordinates

### PR DESCRIPTION
**Pull request by msultan**
- [x] Implement feature / fix bug
 - [x] Add tests
 - [ ] Update changelog

New module to sample and interpret decomposition results via sampling from the trajectories. Added a test to check output type but need to add test to make sure it is sampling the right region .

### CODE REVIEW

**Comment by msultan** [comment]
figshare is down and causing issues.

**Comment by msultan** [comment]
still need to add

- [ ] String sampler to connect arbitrary regions 
- [ ] Coloring method for vmd

**Comment by mpharrigan** [comment]
This needs a better name

**Comment by msultan** [comment]
almost definitely, my idea was ```sample_dimension```, ```sample_region``` and ```connect_regions``` but all 3 are too generic. We should brainstorm this a bit more.

**Comment by cxhernandez** [comment]
`sample_from_decomposition` or `sample_along_component`?

**Comment by msultan** [comment]
@mpharrigan my understanding is that this is now implemented via #768 ?

**Comment by mpharrigan** [comment]
Correct

**Pull request closed without merging**
