### PR TITLE
Remove union dataset

### PR DESCRIPTION
**Pull request by mpharrigan**
This was deprecated. Use featurizer.FeatureUnion instead

### CODE REVIEW

**Comment by mpharrigan** [comment]
Need to remove tests for union_dataset

**Comment by mpharrigan** [comment]
Rebased and finished this PR. waiting for tests to run

**Comment by rmcgibbo** [comment]
I think scipy 0.16.1, which is unfortunately not yet in anacoda (https://github.com/ContinuumIO/anaconda-issues/issues/642) fixes all those damn deprecation warnings.

**Comment by rmcgibbo** [comment]
Or scipy 0.17, also not in anaconda :(

**Pull request merged**
